// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateActivity(arg1, arg2) {
  return window['go']['controllers']['ActivityHandler']['CreateActivity'](arg1, arg2);
}

export function DeleteActivity(arg1) {
  return window['go']['controllers']['ActivityHandler']['DeleteActivity'](arg1);
}

export function UpdateActivity(arg1, arg2) {
  return window['go']['controllers']['ActivityHandler']['UpdateActivity'](arg1, arg2);
}
