// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function GetCalendar(arg1:string,arg2:string,arg3:model.User):Promise<Array<model.Microcycle>>;

export function GetMicrocycle(arg1:string,arg2:string,arg3:model.User):Promise<model.Microcycle>;

export function GetNextNMicrocycles(arg1:string,arg2:string,arg3:number,arg4:model.User):Promise<Array<model.Microcycle>>;

export function GetPreviousNMicrocycles(arg1:string,arg2:string,arg3:number,arg4:model.User):Promise<Array<model.Microcycle>>;
