// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateActivity(arg1) {
  return window['go']['controllers']['ActivityHandler']['CreateActivity'](arg1);
}

export function DeleteActivity(arg1) {
  return window['go']['controllers']['ActivityHandler']['DeleteActivity'](arg1);
}

export function GetActivity(arg1) {
  return window['go']['controllers']['ActivityHandler']['GetActivity'](arg1);
}

export function GetMostRecentDate() {
  return window['go']['controllers']['ActivityHandler']['GetMostRecentDate']();
}

export function UpdateActivity(arg1) {
  return window['go']['controllers']['ActivityHandler']['UpdateActivity'](arg1);
}
