// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateActivityEquipment(arg1) {
  return window['go']['controllers']['EquipmentHandler']['CreateActivityEquipment'](arg1);
}

export function CreateEquipment(arg1, arg2) {
  return window['go']['controllers']['EquipmentHandler']['CreateEquipment'](arg1, arg2);
}

export function DeleteActivityEquipment(arg1) {
  return window['go']['controllers']['EquipmentHandler']['DeleteActivityEquipment'](arg1);
}

export function DeleteEquipment(arg1) {
  return window['go']['controllers']['EquipmentHandler']['DeleteEquipment'](arg1);
}

export function List(arg1) {
  return window['go']['controllers']['EquipmentHandler']['List'](arg1);
}

export function ListEquipmentTypes() {
  return window['go']['controllers']['EquipmentHandler']['ListEquipmentTypes']();
}

export function UpdateActivityEquipment(arg1, arg2) {
  return window['go']['controllers']['EquipmentHandler']['UpdateActivityEquipment'](arg1, arg2);
}

export function UpdateEquipment(arg1, arg2) {
  return window['go']['controllers']['EquipmentHandler']['UpdateEquipment'](arg1, arg2);
}
