// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CreateActivityEquipment(arg1:model.ActivityEquipment):Promise<model.ActivityEquipment>;

export function CreateEquipment(arg1:model.Equipment):Promise<model.Equipment>;

export function DeleteActivityEquipment(arg1:number):Promise<void>;

export function DeleteEquipment(arg1:number):Promise<void>;

export function List():Promise<Array<model.Equipment>>;

export function ListEquipmentTypes():Promise<Array<model.EquipmentType>>;

export function UpdateActivityEquipment(arg1:number,arg2:model.ActivityEquipment):Promise<model.ActivityEquipment>;

export function UpdateEquipment(arg1:number,arg2:model.Equipment):Promise<model.Equipment>;
