// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {time} from '../models';
import {model} from '../models';

export function GetCalendar(arg1:time.Time,arg2:time.Time):Promise<Array<model.Microcycle>>;

export function GetMicrocycle(arg1:time.Time,arg2:time.Time):Promise<model.Microcycle>;

export function GetNextNMicrocycles(arg1:time.Time,arg2:time.Time,arg3:number):Promise<Array<model.Microcycle>>;

export function GetPreviousNMicrocycles(arg1:time.Time,arg2:time.Time,arg3:number):Promise<Array<model.Microcycle>>;
