// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCalendar(arg1, arg2, arg3) {
  return window['go']['controllers']['MicrocycleHandler']['GetCalendar'](arg1, arg2, arg3);
}

export function GetMicrocycle(arg1, arg2, arg3) {
  return window['go']['controllers']['MicrocycleHandler']['GetMicrocycle'](arg1, arg2, arg3);
}

export function GetNextNMicrocycles(arg1, arg2, arg3, arg4) {
  return window['go']['controllers']['MicrocycleHandler']['GetNextNMicrocycles'](arg1, arg2, arg3, arg4);
}

export function GetPreviousNMicrocycles(arg1, arg2, arg3, arg4) {
  return window['go']['controllers']['MicrocycleHandler']['GetPreviousNMicrocycles'](arg1, arg2, arg3, arg4);
}
