// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {time} from '../models';
import {model} from '../models';
import {controllers} from '../models';

export function GetNCycleSummary(arg1:time.Time,arg2:time.Time):Promise<model.NCycleSummary>;

export function GetNextPrevious(arg1:time.Time,arg2:time.Time):Promise<controllers.NextPrevious>;
