// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {controllers} from '../models';

export function GetNCycleSummary(arg1:string,arg2:string):Promise<model.NCycleSummary>;

export function GetNextPrevious(arg1:string,arg2:string):Promise<controllers.NextPrevious>;
