// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthenticateUser(arg1) {
  return window['go']['controllers']['UserHandler']['AuthenticateUser'](arg1);
}

export function CreateStravaToken(arg1, arg2) {
  return window['go']['controllers']['UserHandler']['CreateStravaToken'](arg1, arg2);
}

export function CreateUser(arg1) {
  return window['go']['controllers']['UserHandler']['CreateUser'](arg1);
}

export function GetMicrocycleCurrentDates() {
  return window['go']['controllers']['UserHandler']['GetMicrocycleCurrentDates']();
}

export function GetStravaToken(arg1) {
  return window['go']['controllers']['UserHandler']['GetStravaToken'](arg1);
}

export function UpdateUser(arg1) {
  return window['go']['controllers']['UserHandler']['UpdateUser'](arg1);
}

export function UpdateorCreateStravaToken(arg1, arg2) {
  return window['go']['controllers']['UserHandler']['UpdateorCreateStravaToken'](arg1, arg2);
}
