// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {controllers} from '../models';
import {model} from '../models';

export function AuthenticateUser(arg1:controllers.authRequest):Promise<model.User>;

export function CreateUser(arg1:model.User):Promise<model.User>;

export function GetMicrocycleCurrentDates():Promise<controllers.MCCurrentDate>;

export function UpdateUser(arg1:model.User):Promise<model.User>;
