// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {controllers} from '../models';
import {model} from '../models';
import {oauth2} from '../models';

export function AuthenticateUser(arg1:controllers.authRequest):Promise<model.User>;

export function CreateStravaToken(arg1:model.User,arg2:oauth2.Token):Promise<void>;

export function CreateUser(arg1:model.User):Promise<model.User>;

export function DeleteStravaToken(arg1:model.User):Promise<void>;

export function GetMicrocycleCurrentDates():Promise<controllers.MCCurrentDate>;

export function GetStravaToken(arg1:model.User):Promise<oauth2.Token>;

export function UpdateUser(arg1:model.User):Promise<model.User>;

export function UpdateorCreateStravaToken(arg1:model.User,arg2:oauth2.Token):Promise<void>;
