// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackfillData(arg1, arg2) {
  return window['go']['strava']['Strava']['BackfillData'](arg1, arg2);
}

export function GetNewData(arg1, arg2, arg3) {
  return window['go']['strava']['Strava']['GetNewData'](arg1, arg2, arg3);
}

export function OpenStravaAuth() {
  return window['go']['strava']['Strava']['OpenStravaAuth']();
}

export function RevokeAccess(arg1) {
  return window['go']['strava']['Strava']['RevokeAccess'](arg1);
}

export function StartListener() {
  return window['go']['strava']['Strava']['StartListener']();
}
