// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenStravaAuth():Promise<void>;

export function StartListener():Promise<void>;
