// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenStravaAuth() {
  return window['go']['strava']['Strava']['OpenStravaAuth']();
}

export function StartListener() {
  return window['go']['strava']['Strava']['StartListener']();
}
