// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HasUser() {
  return window['go']['main']['App']['HasUser']();
}

export function LoadUser() {
  return window['go']['main']['App']['LoadUser']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function SetUser(arg1) {
  return window['go']['main']['App']['SetUser'](arg1);
}
