// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function ExportDatabase():Promise<void>;

export function HasUser():Promise<boolean>;

export function LoadUser():Promise<model.User>;

export function Logout():Promise<void>;

export function SetUser(arg1:model.User):Promise<void>;
